package org.skyapps.neatdesign.appdirect.integration

enum AppEvent {
	SUBSCRIPTION_ORDER, SUBSCRIPTION_CHANGE, SUBSCRIPTION_CANCEL, SUBSCRIPTION_NOTICE, ADD_USER, USER_ASSIGNMENT, USER_UNASSIGNMENT
}
